<!DOCTYPE html>
<html lang="en-GB">
<head>
    <meta charset="UTF-8">
    <title>Commit You Git! | The To-Do List Tracker</title>
    <link rel="stylesheet" href="/css/style.css" type="text/css">
</head>
<body>

<h1>Your To-Do List:</h1>

<?php
$output = '';
foreach ($toDos as $toDo){
    $id = $toDo['id'];
    $completed = $toDo['completed'];
    if ($completed == 0){
        $output .="<h2>Thing to do no." . $id . ": " . $toDo['name'] . "</h2>
                <form action='/completed' method='post'>
                    <input name='id' value='" . $id . "' type='hidden'>
                    <input type='submit' name='completed' value='completed'>
                </form>
                <form action='/delete' method='post'>
                    <input name='id' value='" . $id . "' type='hidden'>
                    <input type='submit' name='delete' value='delete'>
                </form>";
    }
}
echo $output;
?>

<h2>Add Thing To Do</h2>
<form action="/add" method="post" >
    <input name="name" type="text">
    <input type="submit" value="Add To Do">
</form>

</body>
</html>