<!DOCTYPE html>
<html lang="en-GB">
<head>
    <meta charset="UTF-8">
    <title>COMMIT | Get It Done</title>
    <script type="text/javascript" src="/js/nav.js" defer></script>
    <script type="text/javascript" src="/js/edit.js" defer></script>
    <link href="https://fonts.googleapis.com/css?family=Alata&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="/css/style.css" type="text/css">
</head>
<body>

<nav>
    <div class="logoContainer">
        <div class="logo">
            COMMIT
        </div>
    </div>
    <div class="menuContainer">
        <ul class="menu">
            <a href="#toDos"><li>TO-DOS</li></a>
            <a href="#add"><li>ADD</li></a>
            <a href="#completed"><li>COMPLETE</li></a>
        </ul>
    </div>
</nav>

<div class="container">

    <div id="toDos">
        <h1>Things To Do:</h1>

        <?php
        echo ToDoApp\helpers\DisplayToDoHelper::displayToDos($toDos);
        ?>
    </div>

    <div class="add" id="add">
        <h1>Add Thing To Do</h1>

        <form action="/add" method="post" >
            <input class='edit' name="name" type="text">
            <input class='button' type="submit" value="Add To Do">
        </form>
    </div>

    <div class="completed" id="completed">
        <h1>Things You've Completed</h1>


        <?php
        echo ToDoApp\helpers\DisplayCompletedToDoHelper::displayCompletedToDos($toDos);
        ?>
    </div>

</div>
</body>
</html>